### ISSUE TITLE
Incorrect statisticts displayed when gstats=hidden or by default

### ISSUE THREAD

**Issue by Unactived** [dz-root/Rootme-readme-stats#1]
From its README description, the `gstats` argument should govern whether or not to show global statistics.

When `gstats=hidden`, the global statistics section should then not appear, and only appear when `gstats=show`.

It currently turns out that when `gstats=hidden`, the global statistics section still appears, and presents incorrect values ; typically the global statistics of another user, more specifically of the last user whose statistics were fetched.

This is particularly problematic as `gstats=hidden` is the default, meaning possibly incorrect statistics are displayed by default.

For example, currently, the following profile shows a rank of 705 (left, `gstats=hidden`) however it really is 804 (right, `gstats=show`) as per [root-me](https://www.root-me.org/Unactive): 

![Unactive](https://root-me-diff.vercel.app/rm-gh?nickname=Unactive&style=dark&gstats=hidden) ![Unactive](https://root-me-diff.vercel.app/rm-gh?nickname=Unactive&style=dark&gstats=show)

URLs behind these pictures are (left then right):

`![Unactive](https://root-me-diff.vercel.app/rm-gh?nickname=Unactive&style=dark&gstats=hidden)`
`![Unactive](https://root-me-diff.vercel.app/rm-gh?nickname=Unactive&style=dark&gstats=show)`

Screenshot of how things look for me in this issue:

![shot](https://github.com/dz-root/Rootme-readme-stats/assets/33038089/7752d641-867d-4791-9abc-2f72f0b38111)

Given the goal of the argument, it should suffice to ensure that no global statistics are displayed at all when `gstats` is not `show`.

**Comment by dz-root** [comment]
Hey @Unactived  thank you for opening this issue. 
Indeed, some variables must be reset each time the server receives a `GET` request.
Fixed here: 21b5837

Let me know if everything is ok, *(make sure you empty your cache before testing).*

**Comment by Unactived** [comment]
Closing since fix appears functional in production.

**Comment by ChrisBuckets** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
egeominotti, @caiodev, @wchh, @ahicham-xyz, @gaonip, @oter2901, @HauExistential, @Mita24474, @ChefXander, @zlatanpham, @tigerlove, @cymjjj123, @jAtlasCode, @fabio-crypto-developer, @chunterb, @shadyscientist, @semyin, @yahorlahunovich, @tianhu288, @kawawa888, @lilpolymath, @phucledien, @Ruslankrutoi, @declan94, @skylightxo, @fantianmi, @sakitkepala, @Leusholy, @wibotoqoye, @HappyLittleFish, @jandranrebbalangue, @SantoshSrinivas79, @tunglt1810, @gearprn, @HayattiQ, @Anuj170122, @ven, @jrussbautista, @nguyenpc, @DevVoxel, @sethzhao, @chase2981, @Meharab, @fundutoojunos, @namlh023, @jordanlepera, @bxsck, @kenplix, @FrankFan, @skraihanCarrotsssw, @NICHOLAS-AGBO, @elvisyjlin, @jiyuunin, @asad112x, @sajad2212, @Mr-Liang93, @MissinA, @0x8400, @dmitrius-org, @rjoshima, @citron03, @srivera145, @brad-luo, @iv7dev, @Flowsmooth, @B8N4S8N, @fairhopeweb, @smatokenfoundation, @Kimyeongsan, @bluesky1020, @0xGosu, @avichavan, @xxxxouo, @seropaski, @nasjp, @runifgg, @billyriantono, @SkalskiP, @chachaxw, @Lumersgo, @OmBayus, @MatteoGauthier, @zzf03680147, @toanhhung86, @ccccqcccc, @tjbtiller, @tyler-he, @JinDotCom, @bapuyunus, @teamzz111, @bowiedi, @chxckj, @banhave, @0xbeny, @goovo, @Necsus, @um1ng, @sun-ks, @Z86-techsongkqx1c, @AllanJunLi, @EazyReal, @yuto-tomita, @savokiss, @fredricen, @scrappy-bot, @kartset, @dijonkitchen, @2552150, @zayzay8998, @CoderApril8, @LuisJoseLopezD, @JimboFromLimbo, @ryoheiwatanabe, @harryhuayuanchong, @WaqasFaridi, @jinke479150, @Facundolavtech, @premnathdey, @q573927428, @billyriantono, @DPS0340, @Nguyenduny, @cheskyherskovic, @cativovo, @sphynxcat222, @mhxw, @tucq88, @ylnhzzl, @mvladk, @michaelc285, @mastercheff-alfajor, @hypenzy, @karooolis, @axel2200, @changmyeong, @AlexeyAbramov, @TrongAnNguyen, @Jaymz, @mohsen-in, @qinhan099, @lijameshao, @agusmade, @chayutzee, @ChefGrey, @guowilling, @vishallamba1988, @Clivern, @tpearson1
